############################# English ############################
[en]
languageName = "En"
title = "Radius"
contentDir = "content"
weight = 1
########### footer content ##########
footer_menu_left = "Community"
footer_menu_middle = "Product"
footer_menu_right = "Support"
footer_content = "Brought to you by the Azure Incubations team"
# copyright
copyright = "© Radius Authors"
